version: '3'

services:
  envoy_redis:
    build:
      context: ./envoy-redis
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./envoy:/etc/envoy
    networks:
      - my-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  new_go_backend:
    build:
      context: ./new_go_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network

  openresty:
    image: openresty/openresty:1.25.3.1-2-alpine-fat
    ports:
      - "8081:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
