version: '3'

services:
  envoy:
    build:
      context: ../envoy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./envoy:/etc/envoy
    networks:
      - my-network



  new_go_backend:
    build:
      context: ../new_go_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network



networks:
  my-network:
    driver: bridge
