version: '3.7'

services:
  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    #image: envoy-backend-envoy:latest 
    ports:
      - "8081:8080"
    volumes:
      - ./envoy:/etc/envoy
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  new_go_backend:
    build:
      context: ../new_go_backend
      dockerfile: Dockerfile
    #image: envoy-backend-new_go_backend:latest  
    ports:
      - "8000:8000"
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G

networks:
  my-network:
    driver: bridge
    #attachable: true 
